Finished .ini parser
Cpp-hw/DnD_console pull request #1
Opened 2016-12-30 00:20 UTC by snaffiwow

#### Usage
```c++
// Class usage for getting data
IniParser* parser = new IniParser("config.ini");
auto params = parser->fGetParams(); // gets all params from file
 
// Class usage for inserting data
map<string, string> ins;
ins.insert({ "Game.board", "1" });
ins.insert({ "Hero.Id", "15" });
parser->fSetParams(ins); // inserts maps data into file
```

2016-12-31 14:08 UTC, NicholasTs requested changes
try to avoid 'throw', as we agreed not to use them, besides we are going to provide servers 100% uptime and easy errors handling. So, to my mind, it is better to provide some errors codes and errors handling via referenced variables or global variables. E.g. "IniParser::fGetParams(int &error_code)".

2016-12-31 14:10 UTC, NicholasTs reviewed
Besides, your code and approach look GREAT!!! Thank you! P.S. waiting for needed changes.

2017-01-03 13:14 UTC, NicholasTs approved these changes

2017-01-03 13:16 UTC, VKopelyuk approved these changes

2017-01-03 13:18 UTC, merged