Data base
Cpp-hw/DnD_console pull request #7
Opened 2017-01-08 20:03 UTC by OlhaLesk

This Database class consists of the following:
- method for openning the connection;
- method for getting data from the database;
- method for putting data into the database.
It receives some SQL query and returns JSON-formatted response.

Inportant information: Use:

SELECT id, username, password, is_active FROM Users;
instead of:

SELECT * FROM Users;

2017-01-08 20:44 UTC, stpetruk approved these changes

2017-01-08 22:32 UTC, NicholasTs requested changes
Olha, your connection method should take at least two parameters - data base name and password. You may also move all the connection routine into constructor with above mentioned parameters.
The second issue is the SHA256 you use. Why do you need it? All hashed data is sent from client or server, no need in using the hsa256 in DB side.

2017-01-09 04:28 UTC, OlhaLesk commented
Ок. I'll move connection method into constructor. But in this case you/server should send me at first some connection request and after my/database positive answer you will be able to send some SQL-query. Have you got some method for this interaction?

2017-01-09 09:46 UTC, NicholasTs commented
@OlhaLesk , you are right! You may not move all the routine into constructor, in this case you would need additional field in your class indicating connection status. Besides, I would like to receive comments or code changes for the whole contend of my request "changes needed".

2017-01-09 14:20 UTC, closed without merging